version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - instamiligram_db
    #command: ./wait-for-it.sh instamiligram_db:5432 > /dev/null 2>&1
    # entrypoint: "./wait-for-it.sh instamiligram_db:5432"

  instamiligram_db:
    image: "postgres:11"
    container_name: "instamiligram_db"
    environment:
      POSTGRES_DB: rainbowDatabase
      POSTGRES_PASSWORD: my_strong_password
      POSTGRES_USER: unicorn_user