version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  instamiligram_db:
    image: "postgres:11"
    container_name: "instamiligram_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rainbowDatabase
      POSTGRES_PASSWORD: my_strong_password
      POSTGRES_USER: unicorn_user